# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 26463f2fdf893f092989ffc4b7c68fca3a7895406a1a317bcf61af23cadcf0b1b51723a031fffed361d46790460ec4d07429db10938fe4ba957bc3001410d685

test:
  secret_key_base: 1af8586cc76524667982b3d6d8ec32a7d91b97dfb81af86da75837ef40d2d1d3d47c4275a61ed83a162815f6e59bdc37eae33e6d9c72046393bd12c61a2c496a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
